frontend/package-lock.json, frontend/package.json, frontend/src/style.css, frontend/src/ui/HeartButton.jsx
메인화면, 저장화면, 정보 상세 페이지, 마이 페이지에 들어가는 하트(저장)버튼을 구현했다.
클릭하면 빈하트에서 빨간 하트로 변하도록 구현했다.
=> feat: 하트 버튼 기능 구현

frontend/src/components/PlaceCard.jsx, frontend/src/style.css
imageUrl (이미지 주소), placeName (장소 이름), location (장소 위치), onSave (저장 여부) 의 props를 전달
=> feat: 장소 카드 구현

frontend/src/components/SearchBar/SearchBar.css, frontend/src/components/SearchBar/SearchBar.jsx
검색창 컴포넌트 구현
handleSearch 함수 내에서 검색 기능 추가할 것
=> feat: 검색창 기능 구현

frontend/src/ui/Button/ButtonModal.jsx
- <ButtonModal>확인/삭제하기/저장하기</ButtonModal> 입력으로 모달 창에서 이용할 버튼
=> feat: 모달 창 버튼 구현

frontend/package-lock.json, frontend/package.json, frontend/src/components/Category/Category.css, frontend/src/components/Category/Category.jsx
=> Feat: 카테고리 구현

frontend/src/ui/Rating.jsx
- 원하는 별점 위치 누르면 앞 별까지 색칠되도록  구현
=> feat: 별점 입력 구현

frontend/src/App.js, frontend/src/pages/MainPage.jsx, frontend/src/styles/MainPage.css
* 메인 페이지 화면 구현 (임시 데이터 사용)
* App.js의 기존 코드 삭제하고 MainPage로 라우팅 설정
=> feat: 메인 페이지 구현

frontend/src/styles/Category.css
카테고리 컨테이너 padding 값을 3px -> 35px로 늘렸습니다.
=> chore: 카테고리 css 수정

frontend/src/App.js, frontend/src/pages/SignupPage.jsx, frontend/src/styles/LoginSignup.css
* 회원가입 페이지 화면 구현
* App.js에 라우팅 추가
=> feat: 회원가입 페이지 구현

frontend/src/App.js
=> chore: 로그인 페이지 라우팅 추가

frontend/src/components/Header/Header.jsx, frontend/src/components/placeCard/PlaceCard.jsx, frontend/src/pages/MainPage/MainPage.jsx
fix: import line
- 디렉터리 구조 변경 이후 import 경로 추가 수정
=> fix: import line

frontend/src/components/Modal/ModalMemo/ModalMemo.jsx, frontend/src/components/Modal/ModalMemo/ModalMemo.style.jsx, frontend/src/components/Modal/index.js, frontend/src/pages/DetailPage/DetailPage.jsx, frontend/src/pages/DetailPage/DetailPage.style.jsx, frontend/yarn.lock
feat: 상세페이지 구현
- 상세페이지 UI 구현
- 등록 모달 창 (캘린더 + 별점) 구현
- API 검토, 수정하기
=> feat: 상세페이지 구현

frontend/src/components/category/Category.jsx, frontend/src/components/searchBar/SearchBar.jsx, frontend/src/pages/SearchResultsPage/SearchResults.style.jsx, frontend/src/pages/SearchResultsPage/SearchResultsPage.jsx
chore: 검색결과 화면으로 이동, 페이지네이션 스타일 적용
- chore: 검색결과 화면으로 이동
- chore: 검색결과 화면에 카테고리 추가
- chore: 페이지네이션 스타일 적용
https://github.com/user-attachments/assets/cb6e6498-e41e-453d-906f-33788a158830
- 검색 결과에서 마지막 페이지 : 좌측 상단부터 정렬
- 검색창에 검색어 유지
=> chore: 검색결과 화면으로 이동, 페이지네이션 스타일 적용

frontend/src/components/Modal/ModalSave/ModalSave.jsx, frontend/src/components/Modal/ModalSave/ModalSave.style.jsx, frontend/src/components/common/Button/HeartButton/HeartButton.jsx, frontend/src/components/common/Button/HeartButton/HeartButton.style.jsx
feat : 저장 버튼 눌렀을 때 나타나는 모달 창 구현
- feat: 카테고리 저장하는 모달창 구현
- feat: 하트 버튼 눌렀을 때 모달창 띄우도록 함
https://github.com/user-attachments/assets/e8a97a46-d257-45c8-9fcc-a3c7c11c596c
- '저장하기' 버튼을 누르지 않더라도 하트 버튼은 그대로 저장된 것으로 뜸 (저장하기 버튼을 눌러야 하트 색 변하도록 수정 필요)
=> feat : 저장 버튼 눌렀을 때 나타나는 모달 창 구현

frontend/src/App.js, frontend/src/components/Header/Header.jsx, frontend/src/pages/LoginSignup/Authentification.jsx, frontend/src/pages/LoginSignup/LoginSignup.style.jsx, frontend/src/pages/LoginSignup/SignupPage.jsx, frontend/src/pages/index.js
Feat: 로그인 여부에 따른 라우팅 설정, 헤더 수정
- chore: 회원가입 화면에 로그인 라우팅 추가
- chore: 헤더 메뉴 수정
- chore: 로그인 회원가입 로고 style 수정
- feat: 로그인 여부에 따른 라우팅 설정, 헤더 수정 (로그인 또는 로그아웃)
https://github.com/user-attachments/assets/b9349245-0a94-4ad3-96bb-1c51bf41da00
- 페이지 렌더링할 때 토큰 저장되어있는지/유효한지 확인하는 방법 찾기
- 백엔드와 api 연동
=> Feat: 로그인 여부에 따른 라우팅 설정, 헤더 수정

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/LoginSignup/LogInContainer.jsx, frontend/src/components/common/Button/index.js, frontend/src/components/common/MemoCard/MemoCard.jsx, frontend/src/components/common/index.js, frontend/src/components/placeCard/PlaceCard.jsx, frontend/src/pages/AccountPage/AccountEditPage.jsx, frontend/src/pages/AccountPage/AccountEditPage.style.jsx, frontend/src/pages/AccountPage/AccountPage.jsx, frontend/src/pages/AccountPage/AccountPage.style.jsx, frontend/src/pages/DetailPage/DetailPage.jsx, frontend/src/pages/InFolderPage/InFolderPage.jsx, frontend/src/pages/SaveListPage/SaveListPage.jsx, frontend/src/pages/index.js, frontend/yarn.lock
feat: 내 계정 페이지 구현 및 라우팅 수정
- 내 계정 페이지 구현 (회원정보 수정 페이지는 모달 창, 데이터 연결 등 추가 작업 필요)
- 기록 모아보기에서 박스를 벗어나는 분량 작성 시 '...'으로 생략됨
- 상세페이지나 폴더 내 페이지로 이동 시 placeName, folderName에 따라 이동하도록 라우팅 
- +api 연동을 위한 axios 설치
https://github.com/user-attachments/assets/7b8ed9e4-abe5-4a98-b328-dad3dd55ebeb
- API 링크 연동
=> feat: 내 계정 페이지 구현 및 라우팅 수정

frontend/src/Api.js, frontend/src/App.js, frontend/src/components/Modal/ModalLogout/ModalLogout.jsx, frontend/src/components/Modal/ModalLogout/ModalLogout.style.jsx, frontend/src/components/category/Category.jsx, frontend/src/components/searchBar/SearchBar.jsx, frontend/src/pages/LoginSignup/Authentification.jsx, frontend/src/pages/LoginSignup/LoginPage.jsx, frontend/src/pages/LoginSignup/LoginSignup.style.jsx, frontend/src/pages/LoginSignup/SignupPage.jsx, frontend/src/pages/MainPage/MainPage.jsx, frontend/src/pages/SearchResultsPage/SearchResultsPage.jsx
Feat : API 연동 코드 작성
- feat: 로그아웃 모달창 구현
- feat: 로그인, 회원가입, 검색화면, 메인화면 api 연동 코드 작성
=> Feat : API 연동 코드 작성

frontend/src/components/Modal/ModalEdit/Edit.jsx, frontend/src/components/Modal/ModalMemo/ModalMemo.jsx, frontend/src/components/common/MemoCard/MemoCard.jsx, frontend/src/components/placeCard/PlaceCard.jsx, frontend/src/pages/AccountPage/AccountPage.jsx, frontend/src/pages/DetailPage/DetailPage.jsx, frontend/src/pages/InFolderPage/InFolderPage.jsx, frontend/src/pages/SaveListPage/SaveListPage.jsx
feat: 상세페이지, 저장목록, 내계정페이지 api 연동
- 상세페이지, 저장목록, 내계정페이지 api 연동
- placeCard 라우팅 수정
=> feat: 상세페이지, 저장목록, 내계정페이지 api 연동

frontend/src/components/Modal/ModalEdit/Edit.jsx, frontend/src/components/common/Error.jsx, frontend/src/components/common/index.js, frontend/src/consts/api.js, frontend/src/pages/AccountPage/AccountPage.jsx, frontend/src/pages/DetailPage/DetailPage.jsx, frontend/src/pages/InFolderPage/InFolderPage.jsx, frontend/src/pages/SaveListPage/SaveListPage.jsx
feat: 공통 api로 정리 / 에러 창 디자인 추가
- 공통 api로 정리
- 에러 창 디자인 추가
- api 연동
=> feat: 공통 api로 정리 / 에러 창 디자인 추가

frontend/src/App.js, frontend/src/components/Header/Header.jsx, frontend/src/components/Modal/ModalLogin/ModalLogin.jsx, frontend/src/components/Modal/ModalLogin/ModalLogin.style.jsx, frontend/src/components/Modal/ModalLogout/ModalLogout.jsx, frontend/src/components/Modal/ModalSignup/ModalSignup.jsx, frontend/src/components/Modal/ModalSignup/ModalSignup.style.jsx, frontend/src/components/category/Category.jsx, frontend/src/pages/LoginSignup/LoginPage.jsx, frontend/src/pages/LoginSignup/SignupPage.jsx, frontend/src/pages/MainPage/MainPage.jsx, frontend/src/pages/SearchResultsPage/SearchResultsPage.jsx
Feat: 목업 데이터
- feat: login signup 팝업창, 플로우 구현
- feat: 검색 결과 데이터 (카페만)
- feat: 메인 화면 데이터
1️⃣ 회원가입, 로그인 플로우
https://github.com/user-attachments/assets/11a8bcdc-9eeb-45c0-a3bd-78fc96d66aef
2️⃣ 메인 화면, 검색 결과 데이터
(‼️ 카테고리의 "카페" 데이터만 넣었습니다.)
https://github.com/user-attachments/assets/8ba4c4e0-a0a1-4c54-a1d2-131e92a7b5ff
=> Feat: 목업 데이터
